apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: # added
      - name: nginx
        image: nginx:1.22.1
        ports:
        - containerPort: 80